In [15]:
# range of the array
import numpy as np
ar1=np.arange(13)
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
#  length of the array
ar1
len(ar1)

13

In [7]:
# convert into multidimentional array
reshape_array=ar1.reshape(13,1)

In [8]:
reshape_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [11]:
# Identity matrix can be created using using 2 functions 
# eye()-->used to define both user defined rows and columns
# identity()-->used to define same number of rows and columns 

# syntax-->np.identity(5n-->5 is 5 row and 5 columns 
# Syntax-->np.eye(3,4p-->3 rows and 4 columns
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
# to convert the array into complex form
np.identity(5,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [16]:
# shape of the array 
ar2=np.arange(25)

In [18]:
ar2.shape

(25,)

In [19]:
# to perform multidimentional slicing
ar2=np.arange(25).reshape(5,5)

In [20]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
# consider shape as property
ar2.shape


(5, 5)

In [22]:
# ar2[rows,columns,step]
# ar2[row_start:row_end,column_start:column_end,step]

ar2[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
ar2


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
# sub array of current array

ar2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [30]:
# negative index values

ar2[-3:-1]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
ar2[-3:-1,-3:-1]

array([[12, 13],
       [17, 18]])

In [33]:
ar3=np.arange(50).reshape(5,10)
# Tasks
# both positive and negative
# 1.)To print 27,28,37,38
# 2.)print 34,35,44,45
# 3.)print 18,19
# 4.)print 30,31,40,41

ar3

ar3

In [43]:
ar3[2:9]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
# lincise

# to add base on column wise axis=0

np.sum(ar3,axis=0)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [40]:
# to add base on row wise axis=1

np.sum(ar3,axis=1)

array([ 45, 145, 245, 345, 445])

In [41]:
# to add base on column wise axis=0

np.sum(ar3,axis=0)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [42]:
# to find the sum of array

np.sum(ar3)

1225

In [46]:
ar3[2:4,6:8]

array([[26, 27],
       [36, 37]])

In [47]:
# mean-->average
# median-->centre value
# mode-->max num of repeated element
# variance-->median/toal num of elements
# std-->square root of variance

In [48]:
# linspace():It is used to print evenly separated points
# between 2 range of values
# Syntax-->linspace(start,end,num of values)
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [49]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [50]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [51]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [84]:
ar3[-3:-1,-3:-1]

array([[27, 28],
       [37, 38]])

In [59]:
ar3[3:5,4:6]

array([[34, 35],
       [44, 45]])

In [60]:
np.linspace(12,30,12,retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [61]:
# random module
# To generate random number between the range

# np.random.randint(start,end)
# np.random.randint(40)
# or

np.random.randint(20,30)

28

In [96]:
ar3[1:2,8:10]

array([[18, 19]])

In [92]:
np.random.rand(4)

array([0.29067649, 0.59646169, 0.98320442, 0.76297322])

In [90]:
# rand()-->
# To get the randomly generated value from 0 to 1,based on
# uniform distribution

np.random.rand(3,4)

array([[0.14507615, 0.57024945, 0.21691294, 0.59908373],
       [0.00293746, 0.93094232, 0.51524106, 0.77133751],
       [0.83077271, 0.29722879, 0.23671271, 0.39492794]])

In [97]:
ar3[-4:-2]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [100]:
# homework
ar3=np.arange(50).reshape(5,10)

In [101]:
ar3


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [105]:
ar3[-4:-3,-3:-1]

array([[17, 18]])

In [107]:
ar3[3:5,0:2]

array([[30, 31],
       [40, 41]])

In [108]:
ar3[2:4,7:9]

array([[27, 28],
       [37, 38]])

In [109]:
ar3[-3:-1,-3:-1]


array([[27, 28],
       [37, 38]])

In [110]:
ar3[3:5,4:6]


array([[34, 35],
       [44, 45]])

In [111]:
ar3[1:2,8:10]


array([[18, 19]])

In [112]:
np.random.randn(5,4)

array([[ 1.31313033,  0.53799856,  0.79861222,  1.58537003],
       [ 0.15781277, -2.67083945,  2.012096  ,  0.32525717],
       [-0.31990461, -2.18743646,  1.49916155, -0.70142757],
       [ 0.57320243,  0.74836596, -1.10272819, -1.19401639],
       [ 0.61826215, -0.84117602,  0.01279123, -1.78521781]])

In [114]:
ar3.min()

0

In [115]:
ar3.max()

49

In [117]:
# To find the index of min values

l1=[56,89,90,67,45]
print(l1.index(67))

3


In [120]:
print(ar3.tolist())

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]


In [123]:
# type of array
type(ar3)

numpy.ndarray

In [124]:
print(ar3.argmin())

0


In [125]:
l1=[56,89,90,67,45]
np1=np.array(l1)

In [126]:
# argmax-->to find the min values index position in an array

print(np1.argmin())

4


In [127]:
# argmin-->to find the max values index position in an array

print(np1.argmax())

2


In [128]:
np.sin(np1)

array([-0.521551  ,  0.86006941,  0.89399666, -0.85551998,  0.85090352])

In [129]:
np.cos(np1)

array([ 0.85322011,  0.51017704, -0.44807362, -0.5177698 ,  0.52532199])

In [130]:
np.tan(np1)

array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [131]:
np.cos(np1)/np.sin(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [132]:
1/np.sin(np1)

array([-1.91735803,  1.16269686,  1.11857241, -1.16887977,  1.17522136])

In [136]:
# task:1->write python code for the below logic
np2=np.array([1,2,3])
np3=np.array([4,5,6])
# (1*4)+(2*5)+(3*6)=4+10+18=->32
sum=(np2[0]*np3[0])+(np2[1]*np3[1])+(np2[2]*np3[2])

In [134]:
print(sum)

4


In [137]:
print(sum)

32


In [138]:
np2=np.array([1,2,3,9])
np3=np.array([4,5,6])
sum=(np2[0]*np3[0])+(np2[1]*np3[1])+(np2[2]*np3[2])+(np2[3]*1)
print(sum)

41


In [140]:
np2=np.array([1,2,3])
np3=np.array([4,5,6])
sum=np2*np3
print(sum.sum())

32


In [141]:
fname=np.array(["sid","fn1","fn2"])
lname=np.array(['T',"ln1","ln2"])
# fname.tostring()

In [148]:
# task1:-->write python code to add below 2 array

np2=np.array([1,2,3,8,3,5,9])
np3=np.array([4,5,6])

len1=len(np2)
len2=len(np3)

diff=abs(len1-len2)
for val in range(diff):
    np3=np.append(np3,1)
    
np.sum((np2*np3))

57

In [151]:
np1=np.array([1,34,56,78,np.nan,np.nan])

In [152]:
np1

array([ 1., 34., 56., 78., nan, nan])

In [153]:
#To print nan values
np1[np.isnan(np1)]

array([nan, nan])

In [154]:
# To eliminate nan values
np1[~np.isnan(np1)]

array([ 1., 34., 56., 78.])

In [155]:
np2=np.array([1,2,3])
np3=np.array([4,5,6])

np.dot(np2,np3)

32

In [156]:
pip list panda


Package                       Version
----------------------------- ---------------
aiobotocore                   2.5.0
aiofiles                      22.1.0
aiohttp                       3.8.5
aioitertools                  0.7.1
aiosignal                     1.2.0
aiosqlite                     0.18.0
alabaster                     0.7.12
anaconda-anon-usage           0.4.2
anaconda-catalogs             0.2.0
anaconda-client               1.12.1
anaconda-cloud-auth           0.1.3
anaconda-navigator            2.5.0
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
async-timeout                 4.0.2
atomicwrites                  1.4.0
attrs                         22.1.0
Automat                       20.2.0
autopep8

In [157]:
# Pandas

import pandas as pd
# Pandas is defined as an open-source library that provides
# high=performance data mnipulates in python
# data analysis requires lot of processing such as restructuring,cleaning,merging,manipulating,etc.....We prefer Pandas to perform above functionalities because it is fast , simple,than other tools.
# Pandas is built on Numpy ,Numpy is required for operating pandas

In [158]:
# Pandas Series:
# It is an data structure with one dimensional labelled array 
# It is a primary building block of DataFrame,making its rows and columns 

In [160]:
labels=['a','b','c']
my_data=[10,20,30]

arr=np.array(my_data)
d={'a':100,"b":200,"c":300}

In [161]:
# Syntax-->pandas.Series(data=None , index=None , dtype=None , name=None , copy=True or False)

# Eg:1
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [162]:
type(pd.Series(my_data))

pandas.core.series.Series

In [163]:
# series with labels

pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [164]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [166]:
pd.Series(data=[print,len,sum])

0    <built-in function print>
1      <built-in function len>
2                  [4, 10, 18]
dtype: object

In [167]:
pd.Series(data=[print(),len,sum])

0                       None
1    <built-in function len>
2                [4, 10, 18]
dtype: object

In [169]:
class profile:
    @property
    def display(self):
        print("My name is sid")
p=profile()
p.display

My name is sid


In [170]:
def greet():
    return "good morning"
print(greet())

good morning


In [175]:
def decor(func):
    def inner():
        str1=func()
        return str1.upper()
    return inner()

def greet():
    return "good morning"
print(decor(greet))

GOOD MORNING


In [177]:
def decor(func):
    def inner():
        str1=func()
        return str1.upper()
    return inner
@decor
def greet():
    return "good morning"
print(greet())

GOOD MORNING


In [182]:
ser1=pd.Series([1,2,3,4,5],['USA',"India","Canada","UK","Egypt"])
ser1

USA       1
India     2
Canada    3
UK        4
Egypt     5
dtype: int64

In [183]:
ser1['USA']

1

In [184]:
# access values using index

ser1[0]

1

In [185]:
ser1[0:3]

USA       1
India     2
Canada    3
dtype: int64

In [187]:
ser2=pd.Series([5,6,7,8],['USA','Brazil','Canada','UK'])
ser1+ser2

Brazil     NaN
Canada    10.0
Egypt      NaN
India      NaN
UK        12.0
USA        6.0
dtype: float64

In [188]:
ser2['china']="duplicate"

In [189]:
ser2

USA               5
Brazil            6
Canada            7
UK                8
china     duplicate
dtype: object

In [190]:
ser2.drop('USA')

Brazil            6
Canada            7
UK                8
china     duplicate
dtype: object

In [191]:
# DataFrame
# pd.DataFrame(datas,row_label,col_label)

In [193]:
df=pd.DataFrame(np.random.randn(5,4))

In [194]:
df

0         1         2         3
0 -0.391169  0.197341 -0.916195 -1.510233
1  0.289948 -0.713466  1.634853  0.079716
2  0.062668  0.287802  0.503256  0.313177
3  0.300040 -2.540550  0.512246 -0.302327
4 -0.264517 -0.852353 -0.038829 -0.587309

In [208]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['w','x','y','z'])

In [209]:
df

w         x         y         z
A -0.294224  0.625662  0.591532 -0.972120
B -1.132146 -0.139956 -0.092848 -0.220046
C -0.149995 -1.398946 -1.710546 -0.040765
D  1.447236  0.481214 -0.787098 -0.779016
E -0.794755 -0.232543 -0.153100 -0.629364

In [197]:
# To convert dictionary to DataFrame

d={"col1":[1,2],"col2":[3,4],"col3":[5,6]}

In [198]:
d

{'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}

In [199]:
df=pd.DataFrame(data=d)

In [200]:
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [201]:
df=pd.DataFrame(d,["row1","row2"])

In [203]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [206]:
df.index

Index(['row1', 'row2'], dtype='object')

In [210]:
df

w         x         y         z
A -0.294224  0.625662  0.591532 -0.972120
B -1.132146 -0.139956 -0.092848 -0.220046
C -0.149995 -1.398946 -1.710546 -0.040765
D  1.447236  0.481214 -0.787098 -0.779016
E -0.794755 -0.232543 -0.153100 -0.629364

In [211]:
df.T

A         B         C         D         E
w -0.294224 -1.132146 -0.149995  1.447236 -0.794755
x  0.625662 -0.139956 -1.398946  0.481214 -0.232543
y  0.591532 -0.092848 -1.710546 -0.787098 -0.153100
z -0.972120 -0.220046 -0.040765 -0.779016 -0.629364

In [212]:
# get all the rows

df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [214]:
# get all the columns

df.columns

Index(['w', 'x', 'y', 'z'], dtype='object')

In [215]:
type(df)

pandas.core.frame.DataFrame

In [216]:
df.dtypes

w    float64
x    float64
y    float64
z    float64
dtype: object

In [217]:
# df.info():To get the information about DataFrame

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   w       5 non-null      float64
 1   x       5 non-null      float64
 2   y       5 non-null      float64
 3   z       5 non-null      float64
dtypes: float64(4)
memory usage: 372.0+ bytes


In [218]:
df.values

array([[-0.29422403,  0.62566177,  0.59153219, -0.97212012],
       [-1.13214613, -0.13995631, -0.09284765, -0.2200459 ],
       [-0.1499949 , -1.39894615, -1.71054628, -0.04076462],
       [ 1.44723649,  0.48121396, -0.78709756, -0.77901646],
       [-0.79475512, -0.23254321, -0.15310033, -0.62936384]])

In [219]:
df.axes

[Index(['A', 'B', 'C', 'D', 'E'], dtype='object'),
 Index(['w', 'x', 'y', 'z'], dtype='object')]

In [220]:
df.ndim

2

In [221]:
df.size

20

In [222]:
# To access specific column in df

df

w         x         y         z
A -0.294224  0.625662  0.591532 -0.972120
B -1.132146 -0.139956 -0.092848 -0.220046
C -0.149995 -1.398946 -1.710546 -0.040765
D  1.447236  0.481214 -0.787098 -0.779016
E -0.794755 -0.232543 -0.153100 -0.629364

In [223]:
df['w']

A   -0.294224
B   -1.132146
C   -0.149995
D    1.447236
E   -0.794755
Name: w, dtype: float64

In [224]:
type(df['w'])

pandas.core.series.Series

In [225]:
# To access multiple columns 

df[['w','x','y']]

w         x         y
A -0.294224  0.625662  0.591532
B -1.132146 -0.139956 -0.092848
C -0.149995 -1.398946 -1.710546
D  1.447236  0.481214 -0.787098
E -0.794755 -0.232543 -0.153100

In [226]:
# To create new column 

df['new']=df['w']+df['y']

In [227]:
df

w         x         y         z       new
A -0.294224  0.625662  0.591532 -0.972120  0.297308
B -1.132146 -0.139956 -0.092848 -0.220046 -1.224994
C -0.149995 -1.398946 -1.710546 -0.040765 -1.860541
D  1.447236  0.481214 -0.787098 -0.779016  0.660139
E -0.794755 -0.232543 -0.153100 -0.629364 -0.947855

In [229]:
df.drop('new',axis=1)

w         x         y         z
A -0.294224  0.625662  0.591532 -0.972120
B -1.132146 -0.139956 -0.092848 -0.220046
C -0.149995 -1.398946 -1.710546 -0.040765
D  1.447236  0.481214 -0.787098 -0.779016
E -0.794755 -0.232543 -0.153100 -0.629364

In [230]:
df

w         x         y         z       new
A -0.294224  0.625662  0.591532 -0.972120  0.297308
B -1.132146 -0.139956 -0.092848 -0.220046 -1.224994
C -0.149995 -1.398946 -1.710546 -0.040765 -1.860541
D  1.447236  0.481214 -0.787098 -0.779016  0.660139
E -0.794755 -0.232543 -0.153100 -0.629364 -0.947855

In [231]:
df.drop('new',axis=1,inplace=True)

In [232]:
df

w         x         y         z
A -0.294224  0.625662  0.591532 -0.972120
B -1.132146 -0.139956 -0.092848 -0.220046
C -0.149995 -1.398946 -1.710546 -0.040765
D  1.447236  0.481214 -0.787098 -0.779016
E -0.794755 -0.232543 -0.153100 -0.629364