In [2]:
import numpy as np
arr=np.array([[1,2,3],[45,6,78],[89,90,6]])
print("Original Array",arr)

Original Array [[ 1  2  3]
 [45  6 78]
 [89 90  6]]


In [3]:
na=np.array([1,2,3])
new_arr=np.r_[arr,[na]]
print("New Array",new_arr)

New Array [[ 1  2  3]
 [45  6 78]
 [89 90  6]
 [ 1  2  3]]


In [5]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.rand(5,4),['A','B','C','D','E'],['w','x','y','z'])

In [6]:
# to access multiple rows
df.loc['A']

w    0.368450
x    0.286013
y    0.100534
z    0.233852
Name: A, dtype: float64

In [7]:
df.loc['B','y']

0.4079602730993862

In [8]:
# to get multiple ordinate
# df.loc[[rows],[columns]]
df.loc[['A','B'],['w','z']]

w         z
A  0.368450  0.233852
B  0.823095  0.248473

In [9]:
# retrive database on the condition
df

w         x         y         z
A  0.368450  0.286013  0.100534  0.233852
B  0.823095  0.544688  0.407960  0.248473
C  0.822292  0.068099  0.823938  0.436656
D  0.443403  0.018291  0.545340  0.882180
E  0.980431  0.150930  0.349243  0.681668

In [10]:
# to get all values greater than 0
df

w         x         y         z
A  0.368450  0.286013  0.100534  0.233852
B  0.823095  0.544688  0.407960  0.248473
C  0.822292  0.068099  0.823938  0.436656
D  0.443403  0.018291  0.545340  0.882180
E  0.980431  0.150930  0.349243  0.681668

In [11]:
df[df>0]

w         x         y         z
A  0.368450  0.286013  0.100534  0.233852
B  0.823095  0.544688  0.407960  0.248473
C  0.822292  0.068099  0.823938  0.436656
D  0.443403  0.018291  0.545340  0.882180
E  0.980431  0.150930  0.349243  0.681668

In [13]:
df['w']>0

A    True
B    True
C    True
D    True
E    True
Name: w, dtype: bool

In [14]:
df[df['w']>0]

w         x         y         z
A  0.368450  0.286013  0.100534  0.233852
B  0.823095  0.544688  0.407960  0.248473
C  0.822292  0.068099  0.823938  0.436656
D  0.443403  0.018291  0.545340  0.882180
E  0.980431  0.150930  0.349243  0.681668

In [15]:
# to handle missing data
df

w         x         y         z
A  0.368450  0.286013  0.100534  0.233852
B  0.823095  0.544688  0.407960  0.248473
C  0.822292  0.068099  0.823938  0.436656
D  0.443403  0.018291  0.545340  0.882180
E  0.980431  0.150930  0.349243  0.681668

In [16]:
d={"A":[1,2,np.nan],"B":[5,np.nan,np.nan],"C":[1,2,3],"D":[np.nan,np.nan,np.nan]}

In [17]:
df1=pd.DataFrame(d)
df1

A    B  C   D
0  1.0  5.0  1 NaN
1  2.0  NaN  2 NaN
2  NaN  NaN  3 NaN

In [18]:
# To drop the values  with nan
# dropna
df1.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [19]:
# dropna(how,thresh,axis,inplace)
df1.dropna(how="all")

A    B  C   D
0  1.0  5.0  1 NaN
1  2.0  NaN  2 NaN
2  NaN  NaN  3 NaN